In [1]:
import numpy as np

In [3]:
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
type(n1)

numpy.ndarray

In [5]:
n2=np.array([[10,20,30,40,50],[70,43,28,90,12]])
n2

array([[10, 20, 30, 40, 50],
       [70, 43, 28, 90, 12]])

In [8]:
n3=np.zeros((5,5))

In [9]:
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
n4=np.zeros((1,2))

In [12]:
n4

array([[0., 0.]])

# For Same value

In [13]:
n5=np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [14]:
n6=np.full((4,8),5)
n6

array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

# NP.ARANGE METHOD FOR DIFFERENT ARRAY VALUES

In [16]:
n7=np.arange(10,20)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
n8=np.arange(10,55,5)
n8

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

# for random values

In [20]:
n9=np.random.randint(1,100,5)
n9

array([63, 42, 37, 39, 67])

# checking the shape of numpy array

In [21]:
n2=np.array([[10,20,30,40,50],[70,43,28,90,12]])
n2.shape

(2, 5)

# To change the shape of exiating array

In [22]:
n2.shape=(5,2)
n2

array([[10, 20],
       [30, 40],
       [50, 70],
       [43, 28],
       [90, 12]])

# vstack,hstack,column_stack

In [24]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [25]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [26]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# intersection & difference

In [28]:
n3=np.array([10,20,30,40,50,60])
n4=np.array([50,60,70,80,90])

In [29]:
np.intersect1d(n3,n4)

array([50, 60])

In [31]:
np.setdiff1d(n3,n4)

array([10, 20, 30, 40])

In [32]:
np.setdiff1d(n4,n3)

array([70, 80, 90])

# Addition of Numpy Array

In [53]:
n1=np.array([10,20,10,30,40,10])
n2=np.array([40,30,70,80,60,69])
np.sum([n1,n2])

469

In [38]:
np.sum([n1,n2],axis=0)

array([50, 50])

In [39]:
np.sum([n1,n2],axis=1)

array([30, 70])

# basic addition,mult,subt,division

In [44]:
n1=n1+1
n1

array([11, 21])

In [45]:
n1=n1*1
n1

array([11, 21])

In [46]:
n1=n1-2
n1

array([ 9, 19])

In [47]:
n1=n1+1
n1

array([10, 20])

In [48]:
n1=n1/2
n1

array([ 5., 10.])

# mean median std deviation

In [57]:
np.mean(n1)

20.0

In [56]:
np.median(n1)

15.0

In [55]:
np.std(n1)

11.547005383792516

# numpy matrix

In [60]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
n1[0]

array([1, 2, 3])

In [63]:
n1[1]

array([4, 5, 6])

In [64]:
n1[2]

array([7, 8, 9])

In [65]:
n1[:,1]

array([2, 5, 8])

In [66]:
n1[:,2]

array([3, 6, 9])

In [67]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# numpy matrix multiplication

In [69]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])
n2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [71]:
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [72]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [73]:
np.save('save_n1',n1)


In [75]:
n12=np.load('save_n1.npy')
n12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])